#ifndef __FBACKUP_IOCTL_H__
#define __FBACKUP_IOCTL_H__

#ifdef _WINDOWS
#include <WinIoCtl.h>
#endif

#define FBACKUP_DRV_NAME_W               L"FBackup"
#define FBACKUP_DRV_NAME_EXT_W           FBACKUP_DRV_NAME_W L".sys"
#define FBACKUP_DRV_NT_DEVICE_NAME_W     L"\\Device\\" FBACKUP_DRV_NAME_W
#define FBACKUP_DRV_DOS_DEVICE_NAME_W    L"\\DosDevices\\" FBACKUP_DRV_NAME_W
#define FBACKUP_DRV_WIN32_DEVICE_NAME_W  L"\\\\.\\" FBACKUP_DRV_NAME_W

enum {
    FBACKUP_DRV_CTL_INIT = 0x801,
    FBACKUP_DRV_CTL_RELEASE,
    FBACKUP_DRV_CTL_TEST,
    FBACKUP_DRV_CTL_ECHO,
    FBACKUP_DRV_CTL_BUGCHECK
};

#define IOCTL_FBACKUP_INIT CTL_CODE( \
    FILE_DEVICE_UNKNOWN, FBACKUP_DRV_CTL_INIT, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_FBACKUP_RELEASE CTL_CODE ( \
    FILE_DEVICE_UNKNOWN, FBACKUP_DRV_CTL_RELEASE, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_FBACKUP_TEST CTL_CODE( \
    FILE_DEVICE_UNKNOWN, FBACKUP_DRV_CTL_TEST, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_FBACKUP_ECHO CTL_CODE( \
    FILE_DEVICE_UNKNOWN, FBACKUP_DRV_CTL_ECHO, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_FBACKUP_BUGCHECK CTL_CODE ( \
    FILE_DEVICE_UNKNOWN, FBACKUP_DRV_CTL_BUGCHECK, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif